### ISSUE TITLE
不回复一下就close了么，应该不要有太多的韭菜上当啊

### ISSUE THREAD

**Issue by volunteer123** [gscsocial/gsc-core#3]

**Comment by EvanYip** [comment]
您好，这个是【光速链 GSC】的定义：

愿景：人人赋能，人人互信

一句话介绍：光速链GSC：全球首个社交操作系统

一段话介绍：光速链GSC是全球首个社交操作系统，同时也是全世界最快最民主最安全的以人为核心的操作系统。

四个特点：

1.以人为核心：全球统一通用账户系统，融合兼容传统社交账号体系；去中心化的价值评估系统；让全天下人人实现一键傻瓜式资产数字化；去中心化的自主链上交易系统；打造区块链上的人类命运共同体。
2.全世界最快：可达数百万级TPS。
3.全世界最民主：ADPOS共识机制：既不是ETH的矿池集权算力垄断的封建主义，又不是EOS的金钱至上一票多投的假民主，而是基于以人为核心以价值为基础的SVN评价模型，实现的最合理最民主的投票机制。
4.全世界最安全：颠覆Facebook等社交网络的数据保护机制。

此次开源只是我们的一个开始，还有大部分代码还会经过严格的测试才会提交更新下来，接下来我们也会持续更新提交的。我们将于 5.13 在北京举办一个比较大型的产品技术发布会，解释会将更详细的内容公布出来。我们的测试网主网也会将于近期上线。

我们是一个实实在在做事情的团队，也 100% 会于近期将更多的源码提交上来，请不要因为只看到了部分信息就着急下结论，谢谢理解、支持和反馈。
